spring.application.name=moeda-estudantil

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/moeda_estudantil
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Initialize data.sql after schema creation
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Server port
server.port=8080

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

