services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: moeda_estudantil
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: